"""empty message

Revision ID: 698304acd69c
Revises: 363c7e7fcd1a
Create Date: 2023-05-16 16:34:39.505427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698304acd69c'
down_revision = '363c7e7fcd1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('submited_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    # ### end Alembic commands ###
